export const indianStates = [
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chhattisgarh",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
  "Andaman and Nicobar Islands",
  "Chandigarh",
  "Dadra and Nagar Haveli and Daman and Diu",
  "Delhi",
  "Jammu and Kashmir",
  "Ladakh",
  "Lakshadweep",
  "Puducherry",
];

export const stateCityMap = {
  "Andhra Pradesh": ["Visakhapatnam", "Vijayawada", "Guntur", "Nellore", "Kurnool", "Tirupati", "Kakinada", "Rajahmundry", "Kadapa"],
  "Arunachal Pradesh": ["Itanagar", "Naharlagun", "Pasighat", "Ziro", "Tawang", "Tezu", "Bomdila", "Khonsa"],
  "Assam": ["Guwahati", "Silchar", "Dibrugarh", "Jorhat", "Nagaon", "Tinsukia", "Tezpur", "Bongaigaon"],
  "Bihar": ["Patna", "Gaya", "Bhagalpur", "Muzaffarpur", "Darbhanga", "Purnia", "Arrah", "Begusarai", "Katihar"],
  "Chhattisgarh": ["Raipur", "Bhilai", "Bilaspur", "Korba", "Durg", "Rajnandgaon", "Raigarh", "Jagdalpur"],
  "Goa": ["Panaji", "Margao", "Vasco da Gama", "Mapusa", "Ponda", "Curchorem", "Bicholim", "Valpoi", "Pernem"],
  "Gujarat": ["Ahmedabad", "Surat", "Vadodara", "Rajkot", "Bhavnagar", "Jamnagar", "Anand", "Navsari", "Gandhinagar", "Morbi"],
  "Haryana": ["Faridabad", "Gurgaon", "Panipat", "Ambala", "Yamunanagar", "Rohtak", "Karnal", "Hisar", "Sonipat"],
  "Himachal Pradesh": ["Shimla", "Dharamshala", "Solan", "Mandi", "Kullu", "Hamirpur", "Chamba", "Una", "Bilaspur"],
  "Jharkhand": ["Ranchi", "Jamshedpur", "Dhanbad", "Bokaro", "Deoghar", "Hazaribagh", "Giridih", "Phusro"],
  "Karnataka": ["Bangalore", "Mysore", "Hubli", "Mangalore", "Belgaum", "Gulbarga", "Davangere", "Shimoga", "Tumkur"],
  "Kerala": ["Thiruvananthapuram", "Kochi", "Kozhikode", "Thrissur", "Kollam", "Alappuzha", "Palakkad", "Kannur", "Kottayam"],
  "Madhya Pradesh": ["Bhopal", "Indore", "Jabalpur", "Gwalior", "Ujjain", "Sagar", "Satna", "Ratlam", "Rewa"],
  "Maharashtra": ["Mumbai", "Pune", "Nagpur", "Thane", "Nashik", "Aurangabad", "Solapur", "Amravati", "Kolhapur", "Navi Mumbai"],
  "Manipur": ["Imphal", "Thoubal", "Bishnupur", "Churachandpur", "Kakching", "Ukhrul", "Senapati", "Jiribam"],
  "Meghalaya": ["Shillong", "Tura", "Jowai", "Cherrapunji", "Nongpoh", "Williamnagar", "Baghmara", "Resubelpara"],
  "Mizoram": ["Aizawl", "Lunglei", "Champhai", "Serchhip", "Kolasib", "Saiha", "Mamit", "Lawngtlai"],
  "Nagaland": ["Kohima", "Dimapur", "Mokokchung", "Wokha", "Zunheboto", "Tuensang", "Phek", "Mon"],
  "Odisha": ["Bhubaneswar", "Cuttack", "Rourkela", "Puri", "Berhampur", "Sambalpur", "Balasore", "Baripada", "Jharsuguda"],
  "Punjab": ["Ludhiana", "Amritsar", "Jalandhar", "Patiala", "Bathinda", "Mohali", "Pathankot", "Hoshiarpur", "Moga"],
  "Rajasthan": ["Jaipur", "Jodhpur", "Kota", "Bikaner", "Udaipur", "Ajmer", "Bhilwara", "Alwar", "Sikar", "Bharatpur"],
  "Sikkim": ["Gangtok", "Namchi", "Gyalshing", "Mangan", "Rangpo", "Jorethang", "Singtam", "Nayabazar"],
  "Tamil Nadu": ["Chennai", "Coimbatore", "Madurai", "Tiruchirappalli", "Salem", "Tirunelveli", "Erode", "Vellore", "Thanjavur", "Tuticorin"],
  "Telangana": ["Hyderabad", "Warangal", "Nizamabad", "Khammam", "Karimnagar", "Ramagundam", "Mahbubnagar", "Nalgonda"],
  "Tripura": ["Agartala", "Udaipur", "Dharmanagar", "Kailasahar", "Ambassa", "Belonia", "Khowai", "Sonamura"],
  "Uttar Pradesh": ["Lucknow", "Kanpur", "Ghaziabad", "Agra", "Varanasi", "Meerut", "Allahabad", "Bareilly", "Aligarh", "Moradabad"],
  "Uttarakhand": ["Dehradun", "Haridwar", "Roorkee", "Haldwani", "Rudrapur", "Rishikesh", "Kashipur", "Pithoragarh"],
  "West Bengal": ["Kolkata", "Howrah", "Durgapur", "Asansol", "Siliguri", "Kharagpur", "Malda", "Burdwan", "Baharampur"],
  "Andaman and Nicobar Islands": ["Port Blair", "Garacharma", "Bambooflat", "Prothrapur", "Mayabunder", "Diglipur", "Rangat"],
  "Chandigarh": ["Chandigarh", "Manimajra", "Sarangpur", "Hallomajra", "Danas", "Behlana", "Khuda Alisher"],
  "Dadra and Nagar Haveli and Daman and Diu": ["Daman", "Diu", "Silvassa", "Amli", "Bhimpore", "Dadra", "Dunetha"],
  "Delhi": ["New Delhi", "North Delhi", "South Delhi", "East Delhi", "West Delhi", "Central Delhi", "Dwarka", "Rohini"],
  "Jammu and Kashmir": ["Srinagar", "Jammu", "Anantnag", "Baramulla", "Kathua", "Samba", "Udhampur", "Sopore"],
  "Ladakh": ["Leh", "Kargil", "Diskit", "Padum", "Drass", "Shey", "Chushul", "Hunder"],
  "Lakshadweep": ["Kavaratti", "Agatti", "Minicoy", "Andrott", "Amini", "Kalpeni", "Kiltan", "Kadmat"],
  "Puducherry": ["Puducherry", "Karaikal", "Mahe", "Yanam", "Ozhukarai", "Ariyankuppam", "Villianur"],
};

export const getCitiesByState = (state) => {
  return stateCityMap[state] || [];
};

// Pincode validation ranges (simplified)
export const statePincodeRanges = {
    "Andhra Pradesh": { start: 500000, end: 535999 },
    "Arunachal Pradesh": { start: 790000, end: 792999 },
    "Assam": { start: 781000, end: 788999 },
    "Bihar": { start: 800000, end: 855999 },
    "Chhattisgarh": { start: 490000, end: 497999 },
    "Goa": { start: 403000, end: 403999 },
    "Gujarat": { start: 360000, end: 396999 },
    "Haryana": { start: 121000, end: 136999 },
    "Himachal Pradesh": { start: 171000, end: 177999 },
    "Jharkhand": { start: 813000, end: 835999 },
    "Karnataka": { start: 560000, end: 591999 },
    "Kerala": { start: 670000, end: 695999 },
    "Madhya Pradesh": { start: 450000, end: 488999 },
    "Maharashtra": { start: 400000, end: 445999 },
    "Manipur": { start: 795000, end: 795999 },
    "Meghalaya": { start: 793000, end: 794999 },
    "Mizoram": { start: 796000, end: 796999 },
    "Nagaland": { start: 797000, end: 798999 },
    "Odisha": { start: 750000, end: 770999 },
    "Punjab": { start: 140000, end: 160999 },
    "Rajasthan": { start: 300000, end: 345999 },
    "Sikkim": { start: 737000, end: 737999 },
    "Tamil Nadu": { start: 600000, end: 643999 },
    "Telangana": { start: 500000, end: 509999 },
    "Tripura": { start: 799000, end: 799999 },
    "Uttar Pradesh": { start: 200000, end: 285999 },
    "Uttarakhand": { start: 244000, end: 263999 },
    "West Bengal": { start: 700000, end: 743999 },
    "Delhi": { start: 110000, end: 110099 },
};

export const validatePincode = (pincode, state) => {
    const range = statePincodeRanges[state];
    if (!range) return true; // Allow if state not in range map
    
    const pin = parseInt(pincode);
    return pin >= range.start && pin <= range.end;
};
